//
//  HouseholdService.swift
//  Home Management
//
//  Created by Jared Nash on 2/4/26.
//
import Foundation
import Supabase

private struct HouseholdInsert: Encodable {
    let name: String
    let created_by: String
}

private struct HouseholdMemberInsert: Encodable {
    let household_id: String
    let user_id: String
    let member_role: String
}

private struct ProfileRoleRow: Decodable {
    let role: UserRole?
}

struct HouseholdService {

    static func createHousehold(name: String) async throws -> HouseholdRow {
        let client = SupabaseManager.shared.client
        guard let uid = client.auth.currentUser?.id else {
            throw NSError(domain: "HouseholdService", code: 0, userInfo: [NSLocalizedDescriptionKey: "Not signed in"])
        }

        // 1) create household (invite_code is auto-generated by DB)
        let householdPayload = HouseholdInsert(
            name: name,
            created_by: uid.uuidString
        )

        let households: [HouseholdRow] = try await client
            .from("households")
            .insert(householdPayload)
            .select()
            .execute()
            .value

        guard let household = households.first else {
            throw NSError(domain: "HouseholdService", code: 1, userInfo: [NSLocalizedDescriptionKey: "No household returned"])
        }

        // 2) create membership row (creator should be parent)
        let memberPayload = HouseholdMemberInsert(
            household_id: household.id.uuidString,
            user_id: uid.uuidString,
            member_role: UserRole.parent.rawValue
        )

        _ = try await client
            .from("household_members")
            .insert(memberPayload)
            .execute()

        return household
    }

    static func joinHousehold(inviteCode: String) async throws -> HouseholdRow {
        let client = SupabaseManager.shared.client
        guard let uid = client.auth.currentUser?.id else {
            throw NSError(domain: "HouseholdService", code: 0, userInfo: [NSLocalizedDescriptionKey: "Not signed in"])
        }

        // Normalize the invite code (trim + uppercase)
        let cleaned = inviteCode.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()

        // Load the signed-in user's profile role so parents join as parents and children as children.
        let profileRows: [ProfileRoleRow] = try await client
            .from("profiles")
            .select("role")
            .eq("id", value: uid.uuidString)
            .limit(1)
            .execute()
            .value

        let memberRole = profileRows.first?.role?.rawValue ?? UserRole.child.rawValue

        // Use RPC to join by invite and return the household id
        let response = try await client
            .rpc("join_household_by_invite", params: ["p_invite_code": cleaned, "p_member_role": memberRole])
            .execute()

        // Parse the returned UUID string from the RPC response data
        let householdIdString = String(data: response.data, encoding: .utf8) ?? ""
        let trimmedId = householdIdString.trimmingCharacters(in: CharacterSet(charactersIn: "\"\n "))
        guard let householdId = UUID(uuidString: trimmedId) else {
            throw NSError(domain: "HouseholdService", code: 3, userInfo: [NSLocalizedDescriptionKey: "Invalid household id returned from server"])
        }

        // Fetch the household by id (will work after membership exists)
        let households: [HouseholdRow] = try await client
            .from("households")
            .select()
            .eq("id", value: householdId.uuidString)
            .limit(1)
            .execute()
            .value

        guard let household = households.first else {
            throw NSError(domain: "HouseholdService", code: 4, userInfo: [NSLocalizedDescriptionKey: "Household not found after joining"])
        }

        return household
    }

    static func fetchMyHousehold() async throws -> HouseholdRow? {
        let client = SupabaseManager.shared.client
        guard let uid = client.auth.currentUser?.id else { return nil }
        // Fetch the most recent membership then fetch the household
        struct Membership: Decodable { let household_id: UUID; let created_at: Date? }
        let memberships: [Membership] = try await client
            .from("household_members")
            .select()
            .eq("user_id", value: uid.uuidString)
            .order("created_at", ascending: false)
            .limit(1)
            .execute()
            .value

        guard let membership = memberships.first else { return nil }

        let households: [HouseholdRow] = try await client
            .from("households")
            .select()
            .eq("id", value: membership.household_id.uuidString)
            .limit(1)
            .execute()
            .value

        return households.first
    }
    
    struct HouseholdMember: Codable, Identifiable {
        let user_id: UUID
        let member_role: String
        let display_name: String?
        var id: UUID { user_id }
    }

    /// Load members via RPC get_household_members with timeout and return typed rows.
    static func loadMembers(householdId: UUID, timeoutSeconds: Double = 8.0) async throws -> [HouseholdMember] {
        let client = SupabaseManager.shared.client
        let start = DispatchTime.now()
        let timeoutNanos = UInt64(timeoutSeconds * 1_000_000_000)
        while true {
            // Try to fetch
            do {
                let rows: [HouseholdMember] = try await client
                    .rpc("get_household_members", params: ["p_household_id": householdId.uuidString])
                    .execute()
                    .value
                return rows
            } catch {
                // If we hit a cancellation, propagate it
                if Task.isCancelled { throw CancellationError() }
                // If we exceeded timeout, surface a friendly error
                let elapsed = DispatchTime.now().uptimeNanoseconds - start.uptimeNanoseconds
                if elapsed >= timeoutNanos {
                    throw NSError(domain: "HouseholdService", code: 408, userInfo: [NSLocalizedDescriptionKey: "Request timed out. Please try again."])
                }
                // Brief backoff before retrying until timeout expires
                try? await Task.sleep(nanoseconds: 150_000_000)
            }
        }
    }
    /// Load members count for summary display.
    static func loadMembersCount(householdId: UUID) async throws -> Int {
        let rows: [HouseholdMember] = try await loadMembers(householdId: householdId)
        return rows.count
    }

    /// Remove a member via secure RPC. Only call when authorized.
    @discardableResult
    static func removeMember(householdId: UUID, userId: UUID) async throws {
        let client = SupabaseManager.shared.client
        do {
            let params = [
                "p_household_id": householdId.uuidString,
                "p_user_id": userId.uuidString
            ]
            let response = try await client
                .rpc("remove_household_member", params: params)
                .execute()
            // Optional: parse response if your RPC returns something
            #if DEBUG
            if let s = String(data: response.data, encoding: .utf8) {
                print("[HouseholdService] remove_household_member ok: \(s)")
            } else {
                print("[HouseholdService] remove_household_member ok (no body)")
            }
            #endif
        } catch {
            // Log full error for diagnostics
            print("[HouseholdService] remove_household_member error:", error)
            throw error
        }
    }
}

